name: build-and-release-executables.yml

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version (e.g., v1.0.0)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6.1.0
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --windowed --name=PlexFileOrganizer main.py

      - name: Rename executable
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            mv dist/PlexFileOrganizer.exe dist/PlexFileOrganizer-windows.exe
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            mv dist/PlexFileOrganizer dist/PlexFileOrganizer-linux
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            mv dist/PlexFileOrganizer dist/PlexFileOrganizer-macos
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: PlexFileOrganizer-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v6.0.0
        with:
          merge-multiple: true

      - name: List downloaded files (Debugging)
        run: ls -R

      - name: Make files executable (Linux/Mac)
        run: chmod +x PlexFileOrganizer-* || true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
          files: |
            PlexFileOrganizer-linux
            PlexFileOrganizer-windows.exe
            PlexFileOrganizer-macos